route:
  receiver: default

receivers:
  - name: default
    email_configs:
      - to: devnull@example.com
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: '#alerts'
        send_resolved: true
