config:
  scrape_configs:
    - job_name: kubernetes-audit
      static_configs:
        - targets:
            - localhost
          labels:
            job: audit-logs
            __path__: /var/log/kubernetes/audit.log
