global:
  scrape_interval: 5s
scrape_configs:
- job_name: soulsync-backend
  metrics_path: /metrics
  static_configs:
  - targets:
    - host.docker.internal:3000
  exemplars:
    max_exemplars: 50
- job_name: redis-exporter
  static_configs:
  - targets:
    - redis-exporter:9121
- job_name: postgres-exporter
  static_configs:
  - targets:
    - postgres-exporter:9187
- job_name: blackbox-http
  metrics_path: /probe
  params:
    module:
    - http_2xx
  static_configs:
  - targets:
    - http://host.docker.internal:3000/readyz
    - http://host.docker.internal:3000/healthz
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115
- job_name: grafana
  static_configs:
  - targets:
    - grafana:3000
- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100
rule_files:
- /etc/prometheus/rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
