name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Customise how releases are versioned and structured. The `$RESOLVED_VERSION`
# placeholder is computed based on merged pull request labels and the
# version-resolver defined below.

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
      - fix
  - title: '🧰 Maintenance'
    labels:
      - chore
      - refactor
      - deps
  - title: '📝 Documentation'
    labels:
      - docs

# Template for individual changes in the release notes. Pull request number and author
# are automatically injected.
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

# Exclude PRs with these labels from the release notes entirely.
exclude-labels:
  - skip-changelog

# Define how version numbers are bumped when certain labels are present. Without
# any of these labels, the default resolution is patch.
version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - fix
      - bug

# Do not draft a release if these labels are present on the PR.
no-release-labels:
  - skip-release
