version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "backend-deps"]
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    labels: ["dependencies", "frontend-deps"]
