version: '3.9'
services:
  backend:
    build:
      context: ./backend
    container_name: soulsync-backend
    ports:
    - 5000:5000
    env_file:
    - ./backend/.env.example
    environment:
      NODE_ENV: production
    volumes:
    - ./backend/data:/app/data
    - ./backend/public:/app/public
    healthcheck:
      test:
      - CMD
      - wget
      - -qO-
      - http://localhost:5000/api/readyz
      interval: 10s
      timeout: 3s
      retries: 5
    restart: always
  frontend:
    build:
      context: ./frontend
    container_name: soulsync-frontend
    ports:
    - 5173:5173
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:5000
    depends_on:
    - backend
    restart: always
