apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: soulsync
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: frontend
          image: ghcr.io/your-org/soulsync-frontend:latest
          ports: [{ containerPort: 80 }]
          env:
            - name: VITE_API_URL
              value: "http://backend.soulsync.svc.cluster.local:5000"
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "200m", memory: "256Mi" }
