apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soulsync.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels: { app: {{ include "soulsync.name" . }}, tier: frontend }
  template:
    metadata:
      labels: { app: {{ include "soulsync.name" . }}, tier: frontend }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports: [{ containerPort: 80 }]
          env:
            - name: VITE_API_URL
              value: "{{ .Values.env.frontend.VITE_API_URL }}"
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu }}
              memory: {{ .Values.resources.frontend.requests.memory }}
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu }}
              memory: {{ .Values.resources.frontend.limits.memory }}
