{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "soulsync.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "soulsync.fullname" . }}-frontend
                port: { number: 80 }
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "soulsync.fullname" . }}-backend
                port: { number: 5000 }
{{- end }}
