route:
  group_by: ['alertname','service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email-team
  routes:
    - match:
        severity: warning
      receiver: slack-warning
    - match:
        severity: critical
      receiver: slack-critical

receivers:
  - name: email-team
    email_configs:
      - to: soulsyncfrequency@gmail.com
        from: '${ALERT_SMTP_USER}'
        smarthost: '${ALERT_SMTP_HOST}:${ALERT_SMTP_PORT}'
        auth_username: '${ALERT_SMTP_USER}'
        auth_password: '${ALERT_SMTP_PASS}'
  - name: slack-warning
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '${SLACK_CHANNEL_WARN:-#alerts}'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }} ({{ .Status }})'
        text: |
          *Severity:* {{ .CommonLabels.severity }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          {{ if env "GRAFANA_URL" }}[Grafana]({{ env "GRAFANA_URL" }}){{ end }} {{ if env "PROMETHEUS_URL" }}| [Prometheus]({{ env "PROMETHEUS_URL" }}){{ end }}
  - name: slack-critical
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_CRITICAL_URL:-${SLACK_WEBHOOK_URL}}'
        channel: '${SLACK_CHANNEL_CRIT:-#alerts-critical}'
        send_resolved: true
        title: 'CRITICAL: {{ .CommonLabels.alertname }} ({{ .Status }})'
        text: |
          *Severity:* {{ .CommonLabels.severity }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          {{ if env "GRAFANA_URL" }}[Grafana]({{ env "GRAFANA_URL" }}){{ end }} {{ if env "PROMETHEUS_URL" }}| [Prometheus]({{ env "PROMETHEUS_URL" }}){{ end }}
