export const primaryMoleculeRegistry: Record<string, { primaryMolecule: string; source: "registry" }> = {
  "asbestosis": { primaryMolecule: "C60", source: "registry" },
  "osteoporosis": { primaryMolecule: "CaCO3", source: "registry" },
  "alzheimer": { primaryMolecule: "Resveratrol", source: "registry" },
  "schizophrenia": { primaryMolecule: "Lithium", source: "registry" },
  "multiple sclerosis": { primaryMolecule: "Myelin peptide fragment", source: "registry" },
  "parkinson": { primaryMolecule: "L-DOPA", source: "registry" },
  "depression": { primaryMolecule: "5-HTP", source: "registry" },
  "anxiety": { primaryMolecule: "GABA", source: "registry" },
  "asthma": { primaryMolecule: "Magnesium", source: "registry" },
  "diabetes type 2": { primaryMolecule: "Metformin-like fragment", source: "registry" },
  "hypertension": { primaryMolecule: "L-Arginine", source: "registry" },
  "migraine": { primaryMolecule: "Riboflavin (B2)", source: "registry" },
  "hypothyroidism": { primaryMolecule: "Iodine", source: "registry" },
  "hyperthyroidism": { primaryMolecule: "L-Carnitine", source: "registry" },
  "pcos": { primaryMolecule: "Myo-Inositol", source: "registry" },
  "endometriosis": { primaryMolecule: "Progesterone precursor", source: "registry" },
  "ibs": { primaryMolecule: "Butyrate", source: "registry" },
  "ibd": { primaryMolecule: "Curcumin", source: "registry" },
  "ulcerative colitis": { primaryMolecule: "Boswellia", source: "registry" },
  "crohn": { primaryMolecule: "Butyrate", source: "registry" },
  "fatty liver": { primaryMolecule: "Choline", source: "registry" },
  "nafld": { primaryMolecule: "Choline", source: "registry" },
  "insomnia": { primaryMolecule: "Glycine", source: "registry" },
  "adhd": { primaryMolecule: "L-Tyrosine", source: "registry" },
  "autism": { primaryMolecule: "L-Carnitine", source: "registry" },
  "bpd": { primaryMolecule: "L-Theanine", source: "registry" },
  "ptsd": { primaryMolecule: "L-Theanine", source: "registry" },
  "c-ptsd": { primaryMolecule: "L-Theanine", source: "registry" },
  "eczema": { primaryMolecule: "Niacinamide", source: "registry" },
  "psoriasis": { primaryMolecule: "Vitamin D3 (cholecalciferol)", source: "registry" },
  "osteopenia": { primaryMolecule: "CaCO3", source: "registry" },
  "anemia": { primaryMolecule: "Heme iron", source: "registry" },
  "pms": { primaryMolecule: "Magnesium glycinate", source: "registry" },
  "ed": { primaryMolecule: "L-Citrulline", source: "registry" },
  "infertility": { primaryMolecule: "Zinc", source: "registry" },
  "sibo": { primaryMolecule: "Berberine", source: "registry" },
  "h pylori": { primaryMolecule: "Bismuth subsalicylate", source: "registry" },
  "covid long": { primaryMolecule: "NAC", source: "registry" },
  "pasc": { primaryMolecule: "NAC", source: "registry" },
  "neuropathy": { primaryMolecule: "Alpha-lipoic acid", source: "registry" },
  "arthritis": { primaryMolecule: "Collagen peptide", source: "registry" },
  "osteoarthritis": { primaryMolecule: "Collagen peptide", source: "registry" },
  "rheumatoid arthritis": { primaryMolecule: "Curcumin", source: "registry" },
  "gout": { primaryMolecule: "Vitamin C", source: "registry" },
  "kidney stones": { primaryMolecule: "Potassium citrate", source: "registry" },
  "osteonecrosis": { primaryMolecule: "Vitamin K2 (MK-7)", source: "registry" },
  "macular degeneration": { primaryMolecule: "Lutein", source: "registry" },
  "glaucoma": { primaryMolecule: "Resveratrol", source: "registry" },
  "hearing loss": { primaryMolecule: "Magnesium", source: "registry" },
  "tinnitus": { primaryMolecule: "Magnesium", source: "registry" }
};
