apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "soulsync.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
      secretName: {{ include "soulsync.fullname" . }}-tls
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "soulsync.fullname" . }}
                port:
                  number: 80
