apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "soulsync.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "soulsync.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
