apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: soulsync-worker
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: soulsync-worker
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    any: true
