apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: soulsync-backend
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: soulsync-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    any: true
