apiVersion: v1
kind: Namespace
metadata:
  name: aiops
---
apiVersion: v1
kind: Secret
metadata:
  name: aiops-secrets
  namespace: aiops
type: Opaque
stringData:
  PROM_URL: "http://prometheus-server.default.svc"
  PROM_TOKEN: ""
  SLACK_WEBHOOK_URL: ""
  DISCORD_WEBHOOK_URL: ""
  PAGERDUTY_ROUTING_KEY: ""
  AIOPS_DATABASE_URL: "postgres://user:pass@host:5432/dbname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-detector
  namespace: aiops
  labels:
    app: aiops-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiops-detector
  template:
    metadata:
      labels:
        app: aiops-detector
    spec:
      containers:
        - name: detector
          image: ghcr.io/REPLACE_WITH_OWNER/therapy-aiops:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: aiops-secrets
          env:
            - name: AIOPS_METRICS
              value: "http_requests:success_rate,http_requests:latency_p99,therapy:success_rate,kubecost_cluster_cost"
            - name: AIOPS_INTERVAL_SEC
              value: "300"
            - name: AIOPS_Z_THRESH
              value: "3.0"
            - name: AIOPS_VOL_MULT
              value: "2.0"
            - name: AIOPS_PCT_THRESH
              value: "0.2"
            - name: AIOPS_RUNBOOK_ENABLED
              value: "true"
            - name: AIOPS_RUNBOOK_WEBHOOK
              value: "http://runbooks-webhook.runbooks.svc:8080/trigger"
            - name: AIOPS_RUNBOOK_POLICY
              value: "http_requests:success_rate:trend_break;http_requests:latency_p99:level_shift;therapy:success_rate:trend_break"
            - name: RUNBOOK_TARGET_NAMESPACE
              value: "default"
            - name: RUNBOOK_APP_LABEL
              value: "therapy-backend"
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: aiops-detector
  namespace: aiops
  labels:
    app: aiops-detector
spec:
  selector:
    app: aiops-detector
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aiops-detector
  namespace: aiops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: aiops-detector
  endpoints:
    - port: http
      interval: 30s
