apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soulsync
bases:
  - ../../base
images:
  - name: ghcr.io/your-org/soulsync-backend
    newTag: latest
  - name: ghcr.io/your-org/soulsync-frontend
    newTag: latest
