global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'soulsync-backend'
    static_configs:
      - targets: ['backend:3000']
        labels:
          group: 'backend'
    metrics_path: /metrics

rule_files:
  - /etc/prometheus/alerts.yml


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
