name: Docker Build & Publish

on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/soulsync-backend:latest,ghcr.io/${{ github.repository }}/soulsync-backend:sha-${{ github.sha }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/soulsync-frontend:latest,ghcr.io/${{ github.repository }}/soulsync-frontend:sha-${{ github.sha }},ghcr.io/${{ github.repository }}/soulsync-backend:sha-${{ github.sha }}


- name: Cosign sign images (optional)
  if: ${{ secrets.COSIGN_KEY != '' }}
  env:
    COSIGN_EXPERIMENTAL: "true"
  run: |
    echo "${{ secrets.COSIGN_KEY }}" > cosign.key
    echo "${{ secrets.COSIGN_PASSWORD }}" | cosign sign --key cosign.key ghcr.io/${{ github.repository }}/soulsync-backend:sha-${{ github.sha }}
    echo "${{ secrets.COSIGN_PASSWORD }}" | cosign sign --key cosign.key ghcr.io/${{ github.repository }}/soulsync-frontend:sha-${{ github.sha }}
