name: e2e
on:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "E2E stub - run Maestro locally with: maestro test e2e/happy-path.test.yml"
