name: Lint & Build

on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    branches: [ main ]
  pull_request:

jobs:
  lint_build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci

      - name: Lint backend
        run: cd backend && npx eslint src --ext .ts

      - name: Lint frontend
        run: cd frontend && npx eslint src --ext .ts,.tsx

      - name: Type check backend
        run: cd backend && npx tsc --noEmit

      - name: Build frontend
        run: cd frontend && npx vite build
