name: sentry-sourcemaps
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    tags:
      - 'v*'
jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (frontend)
        working-directory: ./frontend
        run: npm ci
      - name: Build (with sourcemaps)
        working-directory: ./frontend
        run: npm run build
      - name: Upload sourcemaps to Sentry
        uses: getsentry/action-upload-sourcemaps@v2
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          org: ${{ secrets.SENTRY_ORG }}
          project: ${{ secrets.SENTRY_PROJECT }}
          release: ${{ github.ref_name }}
          sourcemaps: ./frontend/dist
          finalize: true
