image:
  backend:
    repository: ghcr.io/your-org/soulsync-backend
    tag: latest
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/your-org/soulsync-frontend
    tag: latest
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: soulsync.local

resources:
  backend:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  frontend:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

env:
  backend:
    NODE_ENV: production
  frontend:
    VITE_API_URL: http://backend:5000
