global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'soulsync-backend'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['backend:8080']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
