
groups:
- name: soulsync-api-slo
  rules:
  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
    for: 10m
    labels: { severity: page }
    annotations:
      summary: "High 5xx rate (>5%)"
      description: "Investigate recent deployments or external dependencies"
