apiVersion: v1
kind: Service
metadata:
  name: {{ include "soulsync.fullname" . }}-frontend
spec:
  selector: { app: {{ include "soulsync.name" . }}, tier: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
