openapi: 3.0.3
info:
  title: SoulSync API
  version: 0.1.0
servers:
- url: http://localhost:3000
paths:
  /healthz:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /readyz:
    get:
      summary: Readiness check
      responses:
        '200':
          description: Ready
  /api/v1/therapy:
    post:
      summary: Generate therapy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
      responses:
        '200':
          description: Therapy generated
  /api/v1/nutrition:
    post:
      summary: Generate nutrition plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
      responses:
        '200':
          description: Nutrition generated
  /api/v1/admin/audit-logs:
    get:
      summary: List audit logs (admin)
      parameters:
      - in: query
        name: limit
        schema:
          type: integer
          minimum: 1
          maximum: 200
        required: false
        description: Max items (default 50, max 200)
      - in: query
        name: offset
        schema:
          type: integer
          minimum: 0
        required: false
        description: Offset for pagination
      responses:
        '200':
          description: Success
          headers:
            X-Trace-Id:
              schema:
                type: string
              description: Trace correlation ID
        '403':
          description: Forbidden
        '500':
          description: Server error
      security:
      - AdminToken: []
  /api/v1/admin/audit-logs/export-signed:
    get:
      summary: Create signed URL for audit logs export
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - csv
          - json
          - xlsx
      - in: query
        name: ttl
        schema:
          type: integer
          minimum: 60
          maximum: 3600
      - in: query
        name: userId
        schema:
          type: string
      - in: query
        name: status
        schema:
          type: integer
      - in: query
        name: from
        schema:
          type: string
          format: date
      - in: query
        name: to
        schema:
          type: string
          format: date
      responses:
        '200':
          description: Signed URL created
  /api/v1/admin/audit-logs/export-download:
    get:
      summary: Download audit logs using signed token
      parameters:
      - in: query
        name: token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: File or JSON returned
  /api/v1/admin/audit-logs/export-request:
    post:
      summary: Enqueue async export job
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                format:
                  type: string
                  enum:
                  - csv
                  - json
                  - xlsx
                userId:
                  type: string
                status:
                  type: integer
                from:
                  type: string
                  format: date
                to:
                  type: string
                  format: date
      responses:
        '202':
          description: Accepted
  /api/v1/admin/audit-logs/export-status/{id}:
    get:
      summary: Check async export job status
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Job status
  /api/v1/admin/audit-logs/insights:
    get:
      summary: AI/Heuristic insights over audit logs
      parameters:
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: userId
        schema:
          type: string
      - in: query
        name: status
        schema:
          type: integer
      - in: query
        name: from
        schema:
          type: string
          format: date
      - in: query
        name: to
        schema:
          type: string
          format: date
      responses:
        '200':
          description: Insights JSON
  /api/v1/admin/features:
    get:
      summary: Feature flags
      responses:
        '200':
          description: Flags
  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: OpenMetrics exposition
  /api/v1/csp-report:
    post:
      summary: CSP violation reports (report-only)
      requestBody:
        required: false
        content:
          application/csp-report:
            schema:
              type: object
      responses:
        '204':
          description: Accepted (no content)
  /api/v1/health/security:
    get:
      summary: Security flags & headers health
      responses:
        '200':
          description: JSON flags + headers
components:
  securitySchemes:
    AdminToken:
      type: apiKey
      in: header
      name: X-Admin-Token
