name: AI Test Suggestions
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  suggest-tests:
    if: ${{ secrets.OPENAI_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Collect changed files
        id: diff
        run: |
          echo "files=$(jq -c '[.pull_request]')" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/github-script@v7
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request
            const { data: files } = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}/files', { owner: context.repo.owner, repo: context.repo.repo, pull_number: pr.number })
            const diff = files.map(f => `--- ${f.filename}\n${f.patch || ''}`).join('\n')
            const prompt = `Given these diffs, propose 3-7 concrete unit/e2e tests (with file paths) that would best cover the changes. Keep it concise. Diffs:\n${diff}`
            const resp = await fetch("https://api.openai.com/v1/chat/completions", {
              method: "POST",
              headers: { "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`, "Content-Type": "application/json" },
              body: JSON.stringify({ model: "gpt-4o-mini", temperature: 0.2, messages: [{ role:"user", content: prompt }] })
            })
            let body = "AI could not generate suggestions."
            if (resp.ok) {
              const data = await resp.json()
              body = data.choices?.[0]?.message?.content?.trim() || body
            } else {
              body = `AI error: ${resp.status} ${resp.statusText}`
            }
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: pr.number, body })
