
name: ci-quality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install
        working-directory: backend
        run: npm ci || npm install
      - name: Build
        working-directory: backend
        run: npm run build --if-present
      - name: Test
        working-directory: backend
        run: npm test --if-present || echo "tests exited (non-blocking)"
      - name: NPM Audit (non-fatal)
        working-directory: backend
        run: npm audit --omit=dev || true
      - name: SBOM (CycloneDX)
        working-directory: backend
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json || true
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: backend/sbom.json
