name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        node: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json
      - name: Install
        run: npm ci --workspace=backend
      - name: Lint
        run: npm run lint --workspace=backend --if-present
      - name: Typecheck
        run: npm run typecheck --workspace=backend --if-present
      - name: Build
        run: npm run build --workspace=backend


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
