name: Container Scan
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ 'soulsync-backend:ci', 'ghcr.io/soulsyncfrequency/soulsyncapp-backend:latest' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build local image
        if: matrix.image == 'soulsync-backend:ci'
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: soulsync-backend:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ matrix.image }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
