
name: npm-audit
on:
  pull_request:
    paths:
      - 'backend/**'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: cd backend && npm ci
      - name: npm audit --production
        run: cd backend && npm audit --production --audit-level=high
