name: ops-alerts-cron
on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: {}
jobs:
  call-alerts-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call /ops/check-alerts
        env:
          ALERT_ENDPOINT_URL: ${{ secrets.ALERT_ENDPOINT_URL }}
          OPS_ALERT_TOKEN: ${{ secrets.OPS_ALERT_TOKEN }}
        run: |
          if [ -z "$ALERT_ENDPOINT_URL" ]; then
            echo "No endpoint URL configured"; exit 0
          fi
          curl -s -X POST "$ALERT_ENDPOINT_URL"             -H "X-OPS-TOKEN: $OPS_ALERT_TOKEN"             -H "Content-Type: application/json"             --data '{}' || true
