name: Performance Gate (k6)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'   # Mondays 03:00 UTC
  pull_request:

jobs:
  k6:
    if: github.event_name != 'pull_request' || contains(toJson(github.event.pull_request.labels.*.name), 'perf')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        run: npm ci --workspace=backend
      - name: Setup k6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 scenarios
        run: |
          k6 run backend/tests/load/login-refresh-me.js --summary-export=summary-login.json || true
          k6 run backend/tests/load/therapy.js --summary-export=summary-therapy.json || true
          k6 run backend/tests/load/nutrition.js --summary-export=summary-nutrition.json || true
      - name: Perf threshold check (p95 <= 1500ms)
        run: node tools/perf-gate.mjs summary-login.json summary-therapy.json summary-nutrition.json 1500
      - name: Upload k6 summaries
        uses: actions/upload-artifact@v4
        with:
          name: k6-summaries
          path: |
            summary-*.json
            backend/summary-*.json
          if-no-files-found: ignore


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
