coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        only_pulls: true
        informational: false
    patch:
      default:
        target: 80%
        threshold: 0%
        only_pulls: true
        informational: false
comment:
  layout: "reach, diff, flags, files"
  behavior: default
