version: "3.9"
services:
  db:
    image: postgres:16
    container_name: soulsync-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: soulsync
      POSTGRES_PASSWORD: soulsync
      POSTGRES_DB: soulsync
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server:latest
    container_name: soulsync-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-init:
    image: redis:7-alpine
    container_name: soulsync-redis-init
    depends_on:
      redis:
        condition: service_healthy
    entrypoint: ["/bin/sh","-lc"]
    command: ["./backend/redis/init-redisearch.sh"]
    working_dir: /work
    volumes:
      - ./:/work

  prometheus:
    image: prom/prometheus:latest
    container_name: soulsync-prometheus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9090/-/healthy"]
      interval: 15s
      timeout: 5s
      retries: 10
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro\n      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"


redis-exporter:
  image: oliver006/redis_exporter:latest
  container_name: soulsync-redis-exporter
  restart: unless-stopped
  environment:
    - REDIS_ADDR=redis:6379
  ports:
    - "9121:9121"
  depends_on:
    redis:
      condition: service_healthy

postgres-exporter:
  image: quay.io/prometheuscommunity/postgres-exporter
  container_name: soulsync-postgres-exporter
  restart: unless-stopped
  environment:
    - DATA_SOURCE_NAME=postgresql://soulsync:soulsync@db:5432/soulsync?sslmode=disable
  ports:
    - "9187:9187"
  depends_on:
    db:
      condition: service_healthy

blackbox-exporter:
  image: prom/
  container_name: soulsync-blackbox-exporter
  restart: unless-stopped
  ports:
    - "9115:9115"
  volumes:
    - ./prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: soulsync-grafana
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 10
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro



alertmanager:
  image: prom/alertmanager:latest
  container_name: soulsync-alertmanager
  restart: unless-stopped
  ports:
    - "9093:9093"
  volumes:
    - ./observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

volumes:
  db_data:
  redis_data:
