apiVersion: apps/v1
kind: Deployment
metadata:
  name: soulsync-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: APP_ENV
              value: "production"
