name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Print Node & npm versions
        run: |
          node -v
          npm -v

      # --- Backend ---
      - name: Install deps (backend)
        working-directory: ./SoulSyncApp/backend
        run: npm install

      - name: Test (backend) + coverage
        working-directory: ./SoulSyncApp/backend
        run: npm test -- --coverage --passWithNoTests

      # --- Frontend ---
      - name: Install deps (frontend)
        working-directory: ./SoulSyncApp/frontend
        run: npm install

      - name: Test (frontend) + coverage (non-blocking)
        working-directory: ./SoulSyncApp/frontend
        run: npm test -- --coverage --passWithNoTests || echo "no frontend tests"

      # --- Codecov upload ---
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
