name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # --- Backend ---
      - name: Install deps (backend)
        working-directory: backend
        run: npm install

      - name: Test (backend) + coverage
        working-directory: backend
        run: npm test -- --coverage --passWithNoTests

      # --- Frontend ---
      - name: Install deps (frontend)
        working-directory: frontend
        run: npm install

      - name: Test (frontend) + coverage (non-blocking)
        working-directory: frontend
        run: npm test -- --coverage --passWithNoTests || echo "no frontend tests"

      # --- Codecov upload ---
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
