name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend
      - name: Install deps (backend)
        working-directory: backend
        run: npm ci
      - name: Test (backend) + coverage
        working-directory: backend
        run: npm test -- --coverage || npm test -- --coverage --silent

      # Frontend (ako nema testova, neće failati)
      - name: Install deps (frontend)
        working-directory: frontend
        run: npm ci
      - name: Test (frontend) + coverage
        working-directory: frontend
        run: npm test -- --coverage || echo "no frontend tests"

      # Codecov upload (trebaš imati CODECOV_TOKEN u repo Secrets)
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
