name: Dependency Review
on:
  pull_request:
    branches: [main]
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: critical
