name: Release (tag → GitHub Release)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install JS deps
        run: npm ci --prefer-offline --no-audit

      - name: Build release artifacts
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew clean bundleRelease assembleRelease --stacktrace --no-daemon

      - name: Collect artifacts
        run: |
          mkdir -p dist
          cp -r android/app/build/outputs/**/*.aab dist/ 2>/dev/null || true
          cp -r android/app/build/outputs/**/*.apk dist/ 2>/dev/null || true
          cp -r android/app/build/outputs/mapping/release/mapping.txt dist/ 2>/dev/null || true
          ls -R dist || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          generate_release_notes: true
