name: "Validate GitHub secrets"

# This workflow runs on every push or pull request against the main or release branches.
# It fails early if any of the critical environment secrets are missing from the
# repository's Secrets configuration in GitHub. Keeping this list up to date
# prevents broken deploys caused by incomplete configuration.

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required secrets
        shell: bash
        run: |
          # List of required secrets. Update this list whenever you add
          # a new sensitive variable to .env.production or your CI configuration.
          required_secrets=(
            DATABASE_URL
            REDIS_URL
            ADMIN_TOKEN
            ADMIN_JWT_SECRET
            ADMIN_JWT_KEYS
            JWT_SECRET
            REFRESH_SECRET
            EXPORT_SIGNING_SECRET
            AI_API_KEY
            OPENAI_API_KEY
            GITHUB_PACKAGES_TOKEN
            SENTRY_AUTH_TOKEN
            SENTRY_ORG
            SENTRY_PROJECT
            CODECOV_TOKEN
            SLACK_WEBHOOK_URL
            SLACK_WEBHOOK_CRITICAL_URL
            ALERT_SMTP_HOST
            ALERT_SMTP_USER
            ALERT_SMTP_PASS
            GOOGLE_PLAY_JSON
            APPSTORE_KEY_ID
            APPSTORE_ISSUER_ID
            APPSTORE_PRIVATE_KEY
          )

          missing=false
          for secret in "${required_secrets[@]}"; do
            # GitHub exposes secrets as environment variables at runtime. If any
            # required secret is unset or empty, produce a structured error.
            if [ -z "${!secret}" ]; then
              echo "::error file=.github/workflows/secret-check.yml::Secret '$secret' is not configured in the repository Settings."
              missing=true
            fi
          done

          if [ "$missing" = true ]; then
            echo "::error ::One or more required secrets are missing. Please add them under Settings -> Secrets -> Actions."
            exit 1
          fi
